version: '3.8'

services:
  # ⚙️ BACKEND (Spring Boot) - Kay-t-builda w kay-t-lanca
  backend:
    build: 
      context: ./Workflow
      dockerfile: Dockerfile
    container_name: kyntus-backend
    restart: always
    ports:
      - "8082:8082"
    environment:
      # 🔥 THE FIX: N-connectaw l'DB l-qedima li deja kheddama f l'serveur
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.10.10.50:5432/kyntus_db
      - SPRING_DATASOURCE_USERNAME=kyntus_user
      - SPRING_DATASOURCE_PASSWORD=kyntus_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=500MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=500MB

  # 🌐 FRONTEND (Next.js) - Kay-t-builda w kay-t-lanca
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: /api
        BACKEND_URL: http://backend:8082
    container_name: kyntus-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - BACKEND_URL=http://backend:8082