# ===============================
# DATABASE CONFIGURATION (Hybrid: Local + Docker/Prod)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/kyntus_db?reWriteBatchedInserts=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:waeloujdiastral481123456}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=30

# ===============================
# HIBERNATE & JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# LOGS & PERFORMANCE OPTIMIZATION
# ===============================
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=ERROR

# ===============================
# SERVER CONFIGURATION & TIMEOUTS
# ===============================
server.port=${SERVER_PORT:8082}
server.tomcat.connection-timeout=120000
server.tomcat.max-threads=50
server.tomcat.accept-count=100

# ===============================
# MULTIPART / UPLOAD LIMITS
# ===============================
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# ===============================
# ? OMNI SEARCH & JSON FIXES ?
# ===============================
# -1 kat3ni "Accept ay taille dyal JSON" bach l'array dyal les EPS mayt'blokach
server.tomcat.max-http-form-post-size=-1
spring.jackson.default-property-inclusion=non_null